config/routes.rb
Rails.application.routes.draw do
  root 'objectives#index'
  resources :objectives
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/objective.rb
class Objective < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/objectives_controller.rb
class ObjectivesController < ApplicationController
  before_action :set_objective, only: [:show, :edit, :update, :destroy]

  # GET /objectives
  # GET /objectives.json
  def index
    @objectives = Objective.all
  end

  # GET /objectives/1
  # GET /objectives/1.json
  def show
  end

  # GET /objectives/new
  def new
    @objective = Objective.new
  end

  # GET /objectives/1/edit
  def edit
  end

  # POST /objectives
  # POST /objectives.json
  def create
    @objective = Objective.new(objective_params)

    respond_to do |format|
      if @objective.save
        format.html { redirect_to @objective, notice: 'Objective was successfully created.' }
        format.json { render :show, status: :created, location: @objective }
      else
        format.html { render :new }
        format.json { render json: @objective.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /objectives/1
  # PATCH/PUT /objectives/1.json
  def update
    respond_to do |format|
      if @objective.update(objective_params)
        format.html { redirect_to @objective, notice: 'Objective was successfully updated.' }
        format.json { render :show, status: :ok, location: @objective }
      else
        format.html { render :edit }
        format.json { render json: @objective.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /objectives/1
  # DELETE /objectives/1.json
  def destroy
    @objective.destroy
    respond_to do |format|
      format.html { redirect_to objectives_url, notice: 'Objective was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_objective
      @objective = Objective.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def objective_params
      params.require(:objective).permit(:name, :description, :created_at, :updated_at, :deleted_at, :started_on, :ended_on)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/objectives_helper.rb
module ObjectivesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ppobjback</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/objectives/_form.html.erb
<%= form_with(model: objective, local: true) do |form| %>
  <% if objective.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(objective.errors.count, "error") %> prohibited this objective from being saved:</h2>

      <ul>
      <% objective.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :created_at %>
    <%= form.datetime_select :created_at %>
  </div>

  <div class="field">
    <%= form.label :updated_at %>
    <%= form.datetime_select :updated_at %>
  </div>

  <div class="field">
    <%= form.label :deleted_at %>
    <%= form.datetime_select :deleted_at %>
  </div>

  <div class="field">
    <%= form.label :started_on %>
    <%= form.date_select :started_on %>
  </div>

  <div class="field">
    <%= form.label :ended_on %>
    <%= form.date_select :ended_on %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/objectives/edit.html.erb
<h1>Editing Objective</h1>

<%= render 'form', objective: @objective %>

<%= link_to 'Show', @objective %> |
<%= link_to 'Back', objectives_path %>

app/views/objectives/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Objectives</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th>Deleted at</th>
      <th>Started on</th>
      <th>Ended on</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @objectives.each do |objective| %>
      <tr>
        <td><%= objective.name %></td>
        <td><%= objective.description %></td>
        <td><%= objective.created_at %></td>
        <td><%= objective.updated_at %></td>
        <td><%= objective.deleted_at %></td>
        <td><%= objective.started_on %></td>
        <td><%= objective.ended_on %></td>
        <td><%= link_to 'Show', objective %></td>
        <td><%= link_to 'Edit', edit_objective_path(objective) %></td>
        <td><%= link_to 'Destroy', objective, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Objective', new_objective_path %>

app/views/objectives/new.html.erb
<h1>New Objective</h1>

<%= render 'form', objective: @objective %>

<%= link_to 'Back', objectives_path %>

app/views/objectives/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @objective.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @objective.description %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @objective.created_at %>
</p>

<p>
  <strong>Updated at:</strong>
  <%= @objective.updated_at %>
</p>

<p>
  <strong>Deleted at:</strong>
  <%= @objective.deleted_at %>
</p>

<p>
  <strong>Started on:</strong>
  <%= @objective.started_on %>
</p>

<p>
  <strong>Ended on:</strong>
  <%= @objective.ended_on %>
</p>

<%= link_to 'Edit', edit_objective_path(@objective) %> |
<%= link_to 'Back', objectives_path %>